from django.db import models

class User(models.Model):
    name = models.CharField("Name", max_length=240)
    email = models.EmailField()
    document = models.CharField("Document", max_length=20)
    phone = models.CharField(max_length=20)
    registrationDate = models.DateField("Registration Date", auto_now_add=True)

    def __str__(self):
        return self.name


class CASE(models.Model):
    upper_stl = models.CharField("", max_length=100)
    lower_stl = models.CharField("", max_length=100)
    x_ray = models.CharField("", max_length=100)
    upper_png = models.CharField("", max_length=100)
    lower_png = models.CharField("", max_length=100)
    
    def __str__(self):
        return self.name

class X_RAY(models.Model):
    x_ray = models.CharField("", max_length=100)
    upper_jaw_1x = models.FloatField()
    upper_jaw_1y = models.FloatField()
    upper_jaw_2x = models.FloatField()
    upper_jaw_2y = models.FloatField()
    upper_teeth_1x = models.FloatField()
    upper_teeth_1y = models.FloatField()
    upper_teeth_2x = models.FloatField()
    upper_teeth_2y = models.FloatField()
    lower_jaw_1x = models.FloatField()
    lower_jaw_1y = models.FloatField()
    lower_jaw_2x = models.FloatField()
    lower_jaw_2y = models.FloatField()
    lower_teeth_1x = models.FloatField()
    lower_teeth_1y = models.FloatField()
    lower_teeth_2x = models.FloatField()
    lower_teeth_2y = models.FloatField()
    
    def __str__(self):
        return self.name

class UPPER(models.Model):
    upper_png = models.CharField("", max_length=100)
    _1_distal_x = models.FloatField()
    _1_distal_y = models.FloatField()
    _1_mesial_x = models.FloatField()
    _1_mesial_y = models.FloatField()
    _2_distal_x = models.FloatField()
    _2_distal_y = models.FloatField()
    _2_mesial_x = models.FloatField()
    _2_mesial_y = models.FloatField()
    _3_distal_x = models.FloatField()
    _3_distal_y = models.FloatField()
    _3_mesial_x = models.FloatField()
    _3_mesial_y = models.FloatField()
    _4_distal_x = models.FloatField()
    _4_distal_y = models.FloatField()
    _4_mesial_x = models.FloatField()
    _4_mesial_y = models.FloatField()
    _5_distal_x = models.FloatField()
    _5_distal_y = models.FloatField()
    _5_mesial_x = models.FloatField()
    _5_mesial_y = models.FloatField()
    _6_distal_x = models.FloatField()
    _6_distal_y = models.FloatField()
    _6_mesial_x = models.FloatField()
    _6_mesial_y = models.FloatField()
    _7_distal_x = models.FloatField()
    _7_distal_y = models.FloatField()
    _7_mesial_x = models.FloatField()
    _7_mesial_y = models.FloatField()
    _8_distal_x = models.FloatField()
    _8_distal_y = models.FloatField()
    _8_mesial_x = models.FloatField()
    _8_mesial_y = models.FloatField()
    _9_distal_x = models.FloatField()
    _9_distal_y = models.FloatField()
    _9_mesial_x = models.FloatField()
    _9_mesial_y = models.FloatField()
    _10_distal_x = models.FloatField()
    _10_distal_y = models.FloatField()
    _10_mesial_x = models.FloatField()
    _10_mesial_y = models.FloatField()
    _11_distal_x = models.FloatField()
    _11_distal_y = models.FloatField()
    _11_mesial_x = models.FloatField()
    _11_mesial_y = models.FloatField()
    _12_distal_x = models.FloatField()
    _12_distal_y = models.FloatField()
    _12_mesial_x = models.FloatField()
    _12_mesial_y = models.FloatField()
    _13_distal_x = models.FloatField()
    _13_distal_y = models.FloatField()
    _13_mesial_x = models.FloatField()
    _13_mesial_y = models.FloatField()
    _14_distal_x = models.FloatField()
    _14_distal_y = models.FloatField()
    _14_mesial_x = models.FloatField()
    _14_mesial_y = models.FloatField()
    _6L_x = models.FloatField()
    _6L_y = models.FloatField()
    _5L_x = models.FloatField()
    _5L_y = models.FloatField()
    _4L_x = models.FloatField()
    _4L_y = models.FloatField()

    def __str__(self):
        return self.name

class LOWER(models.Model):
    lower_png = models.CharField("", max_length=100)
    _1_distal_x = models.FloatField()
    _1_distal_y = models.FloatField()
    _1_mesial_x = models.FloatField()
    _1_mesial_y = models.FloatField()
    _2_distal_x = models.FloatField()
    _2_distal_y = models.FloatField()
    _2_mesial_x = models.FloatField()
    _2_mesial_y = models.FloatField()
    _3_distal_x = models.FloatField()
    _3_distal_y = models.FloatField()
    _3_mesial_x = models.FloatField()
    _3_mesial_y = models.FloatField()
    _4_distal_x = models.FloatField()
    _4_distal_y = models.FloatField()
    _4_mesial_x = models.FloatField()
    _4_mesial_y = models.FloatField()
    _5_distal_x = models.FloatField()
    _5_distal_y = models.FloatField()
    _5_mesial_x = models.FloatField()
    _5_mesial_y = models.FloatField()
    _6_distal_x = models.FloatField()
    _6_distal_y = models.FloatField()
    _6_mesial_x = models.FloatField()
    _6_mesial_y = models.FloatField()
    _7_distal_x = models.FloatField()
    _7_distal_y = models.FloatField()
    _7_mesial_x = models.FloatField()
    _7_mesial_y = models.FloatField()
    _8_distal_x = models.FloatField()
    _8_distal_y = models.FloatField()
    _8_mesial_x = models.FloatField()
    _8_mesial_y = models.FloatField()
    _9_distal_x = models.FloatField()
    _9_distal_y = models.FloatField()
    _9_mesial_x = models.FloatField()
    _9_mesial_y = models.FloatField()
    _10_distal_x = models.FloatField()
    _10_distal_y = models.FloatField()
    _10_mesial_x = models.FloatField()
    _10_mesial_y = models.FloatField()
    _11_distal_x = models.FloatField()
    _11_distal_y = models.FloatField()
    _11_mesial_x = models.FloatField()
    _11_mesial_y = models.FloatField()
    _12_distal_x = models.FloatField()
    _12_distal_y = models.FloatField()
    _12_mesial_x = models.FloatField()
    _12_mesial_y = models.FloatField()
    _13_distal_x = models.FloatField()
    _13_distal_y = models.FloatField()
    _13_mesial_x = models.FloatField()
    _13_mesial_y = models.FloatField()
    _14_distal_x = models.FloatField()
    _14_distal_y = models.FloatField()
    _14_mesial_x = models.FloatField()
    _14_mesial_y = models.FloatField()
    _6L_x = models.FloatField()
    _6L_y = models.FloatField()
    _5L_x = models.FloatField()
    _5L_y = models.FloatField()
    _4L_x = models.FloatField()
    _4L_y = models.FloatField()

    def __str__(self):
        return self.name

